Project.toml, README.md, demo.jl, deps/wrapper.cc, deps/wrapper.h, src/wrappers/any.jl, test/buffer.jl, test/put_get.jl, test/runtests.jl
Allows us to store any bytes in the object store.
---
- https://app.asana.com/0/0/1205184395990358
=> Generalized Ray `put`/`get`

.github/workflows/Ray_CI.yml
This is slowing us down more than it's helping at the moment. I also removed some unnecessary workflow changes.
=> Run Ray.jl CI workflow on draft PRs

Ray.jl/test/task.jl, src/wrappers/any.jl
---
- https://app.asana.com/0/0/1205338201542037
=> tasks can run no-arg functions

Ray.jl/src/Ray.jl, Ray.jl/src/object_store.jl, Ray.jl/src/runtime.jl, Ray.jl/test/object_store.jl, Ray.jl/test/runtests.jl
---
- https://app.asana.com/0/0/1205319616948328
=> Implement Ray.jl put/get

Ray.jl/src/object_store.jl
merged the previous PR before pushing this change
=> fix docstring

ray_julia_jll/test/put_get.jl, src/object_store.jl, test/task.jl
Work towards #86.
~~Depends on #98~~
=> use `ray_julia_jll.contains` in `get`, add `Base.isready`/`wait` methods

README.md
This is based on feedback from early internal Beacon users.
=> Expanded setup instructions

README.md
=> Tweak build instructions

README.md
https://stackoverflow.com/questions/30239152/specify-extras-require-with-pip-install-e
=> how to install default extra deps from source build

ray_julia_jll/src/expr.jl, ray_julia_jll/src/wrappers/any.jl
=> Fix `getproperty` invalidation in ray_julia_jll

README.md
Took a first pass at updating the instructions due to the changes in https://github.com/beacon-biosignals/Ray.jl/pull/134. @glennmoy feel free to take over this PR.
=> Add pre-built/source install instructions

README.md
=> Correction to Pre-built instructions

.JuliaFormatter.toml, .github/workflows/FormatCheck.yml, README.md, build/bind_artifacts.jl, build/build_library.jl, build/build_tarballs.jl, build/common.jl, build/upload_tarballs.jl, src/Ray.jl, src/exceptions.jl, src/function_manager.jl, src/object_ref.jl, src/ray_julia_jll/common.jl, src/ray_julia_jll/expr.jl, src/ray_serializer.jl, src/runtime.jl, test/exceptions.jl, test/function_manager.jl, test/object_ref.jl, test/object_store.jl, test/ray_julia_jll/function_descriptor.jl, test/ray_julia_jll/reference_counting.jl, test/ray_julia_jll/runtests.jl, test/ray_julia_jll/utils.jl, test/remote_function.jl, test/runtests.jl, test/runtime.jl, test/runtime_env.jl, test/task.jl, test/utils.jl
Should be applying the YAS style guide before our first real release.
=> Apply YAS formatting

.github/workflows/FormatCheck.yml, src/Ray.jl
Confirmed that
- will ~~not~~ format draft PRs
- format errors leave comments with suggestion to fix
- ...except on draft PRs, where the build fails
=> use reviewdog suggestions for format, only on non-draft PRs

Dockerfile
I've been using the `Dockerfile` again and discovered a problem and some outdated instructions.
=> Fixes to Dockerfile

src/ray_serializer.jl, test/ray_serializer.jl, test/runtests.jl
Fixes a bug introduced in #140.
=> Fix `log_deserialization_error` bug

.github/workflows/CI.yml
Should help us address https://github.com/beacon-biosignals/Ray.jl/issues/177.
=> Save Ray CI logs as artifacts

build/wrapper.cc, src/object_ref.jl, src/object_store.jl, src/runtime.jl, test/ray_julia_jll/put_get.jl, test/ray_julia_jll/runtests.jl
=> Return Status from CoreWorker function and remove RAY_CHECK

.github/workflows/CI.yml
Working off of #194 in an attempt to get `actions/download-artifact` working
=> Attempt using `actions/download-artifact`

.github/workflows/FormatCheck.yml
Ran into some weird errors in #221 with the FormatCheck workflow so I decided to modernize this workflow to see if it's the workflow or the PR.
=> Refactor the FormatCheck workflow
