beacon-biosignals/Ray.jl

.gitignore, Project.toml, deps/wrapper.cc, deps/wrapper.h, src/wrappers/any.jl, test/gcs_client.jl, test/runtests.jl
Function manager will put/get stuff into the GCS internal key-value store, so a first step is being able to expose the KV store interface to julia.  Unfortunately this is not SO straightforward: the basic `GcsClient` needs a `io_service` (actually a `instrumented_io_service` but same thing basically) to manage the actual async execution of the requests, and the client that's embedded in the `CoreWorkerProcess` itself is private and not accessible via member functions (at least at the level we need) so we can't piggyback on that.  
My solution here is to add a `JuliaGcsClient` wrapper that manages the IO service and the associated thread (based on the GCS client test harness code).  ~~As you can see from my `Disconnect` function, I'm struggling to figure out how to tear this all down when …
=> expose a `GcsClient` wrapper to julia

Project.toml, deps/wrapper.cc, deps/wrapper.h, src/ray_core_worker_julia_jll.jl, src/wrappers/any.jl, test/runtests.jl, test/task.jl
Implements the Julia Ray worker. The order of how things are called is as follows:
1. User runs `ray start --head`
2. The C++ raylet initiates a Julia worker prestart (https://github.com/beacon-biosignals/ray/pull/4) which spawns a Python process running `setup_worker.py`
3. The `setup_worker.py` constructs a command to run under `bash`. This calls `julia -e 'using ray_core_worker_julia_jll; ray_core_worker_julia_jll.start_worker()`
4. The `start_worker` parses the flags passed in and runs the Julia core worker C++ code `initialize_coreworker_worker`
5. Now spawn another Julia process to run as the driver and run the following
```julia
using ray_core_worker_julia_jll: initialize_coreworker, shutdown_coreworker, submit_task, get
initialize_coreworker()
oid = submit_task()
@show get(oid) …
```
=> First pass on using a Julia function as a Ray task

deps/wrapper.cc, deps/wrapper.h, src/wrappers/any.jl
Currently we hardcode the `CoreWorkerOptions` values in both `initialize_coreworker` and `initialize_coreworker_worker` functions. 
These changes allow for `initialize_coreworker_worker` to parse these values from the ray CLI `passthrough` args.
For the `initialize_coreworker` function, we continue to parse the `raylet.out` logs for CLI args.
~~The `raylet_socket` and `store_socket` continue to be hardcoded but I'm almost certain these are sensible defaults anyway.~~
=> Parse CoreWorker options from Ray cli passthrough arguments

Ray.jl/src/Ray.jl, Ray.jl/src/function_manager.jl, Ray.jl/src/runtime.jl, Ray.jl/test/utils.jl, deps/wrapper.cc, deps/wrapper.h, src/wrappers/any.jl, test/runtests.jl, test/utils.jl
This is a followup to #20 and #19 which 
- introduces a global function manager in Ray.jl
- slightly improves initialization and jobid handling (now gets jobid from coreworkerprocess)
- exports function on task submit
- imports function in task executor
I'd say it's still WIP; a _single_ task invocation works great!  even with `submit_task(() -> getpid())`.  but for some reaosn things deadlock on any further task submissions, with no errors in the raylet.err or `julia_worker_$(PID).log` files.
=> integrate function manager and task prototypes

Ray.jl/src/runtime.jl, Ray.jl/test/task.jl, deps/wrapper.cc, deps/wrapper.h, src/wrappers/any.jl
Depends on https://github.com/beacon-biosignals/ray/pull/7.  Partially addresses #30 since it allows multiple workers to be created.  But doesn't fix the underlying issue of not re-using existing worker...
=> pass `--startup_token` through to julia workers

Ray.jl/src/function_manager.jl, Ray.jl/test/function_manager.jl
This is based on the python checks:
thresholds defined here: https://github.com/beacon-biosignals/ray/blob/1c0cddc478fa33d4c244d3c30aba861a77b0def9/python/ray/_private/ray_constants.py#L120-L123
checks executed here: 
https://github.com/beacon-biosignals/ray/blob/1c0cddc478fa33d4c244d3c30aba861a77b0def9/python/ray/_private/utils.py#L725-L767
---
- https://app.asana.com/0/0/1205303690266615
=> check for oversize functions before exporting

Ray.jl/src/runtime.jl
Fixes a mistake introduced in #41. I am surprised Aqua doesn't catch this:
```
┌ Ray [3f779ece-f0b6-4c4f-a81a-0cb2add9eb95]
│  WARNING: Method definition project_dir() in module Ray at /Users/cvogt/.julia/dev/ray_core_worker_julia_jll/Ray.jl/src/runtime_env.jl:15 overwritten at /Users/cvogt/.julia/dev/ray_core_worker_julia_jll/Ray.jl/src/runtime.jl:102.
│    ** incremental compilation may be fatally broken for this module **
└
```
=> Define `project_dir` once

Ray.jl/src/Ray.jl, Ray.jl/src/runtime.jl, Ray.jl/test/runtests.jl, Ray.jl/test/utils.jl, deps/wrapper.cc, deps/wrapper.h, src/wrappers/any.jl, test/utils.jl
Quick cleanup pass:
- Rename `initialize_coreworker_driver` to `initialize_driver`
- Rename `initialize_coreworker_worker` to `initialize_worker`
- Rename `shutdown_coreworker` to `shutdown_driver`
- Rename `ray_core_worker_julia_jll.start_worker` to `ray_core_worker_julia_jll.initialize_worker`
=> Rename initialize/shutdown functions

deps/wrapper.cc
Disabling the output on our CxxWrap finalizer which let's us know which objects are being deleted. It's still useful code when encountering segmentation faults which is why I've opted to comment the code out for now instead of delete it.
=> Silent CxxWrap finalizer

Ray.jl/src/runtime.jl, Ray.jl/test/task.jl, deps/wrapper.cc, src/wrappers/any.jl
the issue was that we were not setting `runtime_env_hash` correctly in the core worker options.
~~the test needs work: currently, it'll spin up more workers to handle the extra load.  informally when I tested htis locally, running the test twice, it does re-use 8 workers (number of CPUs on my macbook air).~~
---
- https://app.asana.com/0/0/1205303690266614
=> re-use workers for multiple tasks

Ray.jl/src/function_manager.jl, Ray.jl/src/runtime.jl, Ray.jl/test/runtests.jl, Ray.jl/test/runtime.jl, deps/wrapper.cc, test/utils.jl
This fixes the issue where all teh core worker logs (including GCS event stats every 1s) were being written to stderr.
I did a tiny bit of refactoring to allow the session dir and logs dir to be passed in as arguments to `Ray.init()`.  Logging to stderr can be turned back on by either passing in `logs_dir=""`, or by setting `RAY_LOG_TO_STDERR=1` (which matches the python driver).  not totally wedded to that but figured it was good to be consistent.
---
- https://app.asana.com/0/0/1205360251811528
=> set logs_dir in options and default to file logging

Ray.jl/src/function_manager.jl, Ray.jl/test/function_manager.jl
Fixes this exception I was seeing regularly on my MacBook:
```julia
function manager: Error During Test at /Users/cvogt/.julia/dev/ray_core_worker_julia_jll/Ray.jl/test/function_manager.jl:23
Test threw exception
Expression: wait_for_function(fm, mfd, jobid; timeout_s = 1) == :timed_out
Unknown: Deadline Exceeded
Stacktrace:
[1] Exists(arg1::Union{JuliaGcsClient, CxxWrap.CxxWrapCore.CxxRef{<:JuliaGcsClient}}, arg2::Union{AbstractString, CxxWrap.CxxWrapCore.ConstCxxRef{<:CxxWrap.StdLib.StdString}, CxxWrap.CxxWrapCore.CxxRef{<:CxxWrap.StdLib.StdString}}, arg3::Union{AbstractString, CxxWrap.CxxWrapCore.ConstCxxRef{<:CxxWrap.StdLib.StdString}, CxxWrap.CxxWrapCore.CxxRef{<:CxxWrap.StdLib.StdString}}, arg4::Integer)
@ ray_core_worker_julia_jll ~/.julia/packages/CxxWrap/aXNBY/src/CxxWrap.jl:624 …
```
=> Fix "Deadline Exceeded" exception

Ray.jl/src/Ray.jl, Ray.jl/src/object_store.jl, Ray.jl/src/runtime.jl, Ray.jl/test/runtests.jl, Ray.jl/test/runtime.jl, deps/wrapper.cc, src/wrappers/any.jl
Should improve performance for Ray task calls which use small sized arguments.
=> Support inlining task arguments

Ray.jl/src/runtime.jl
There are log messages we're printing before we set up the file logger which don't get flushed until the worker shuts down, so better to do this before anything else.
=> move logfile initialization to top of `start_worker`

Ray.jl/src/Ray.jl, Ray.jl/src/object_ref.jl, Ray.jl/src/object_store.jl, Ray.jl/src/runtime.jl, Ray.jl/test/object_ref.jl, Ray.jl/test/object_store.jl, Ray.jl/test/runtests.jl, Ray.jl/test/task.jl, deps/wrapper.cc, src/wrappers/any.jl
Introduces the `ObjectRef` Julia object which is the Julian interface for dealing with object references. This is similar to how Python handles things. Having this struct allows us to hide the internals of using C++ `ObjectID`s from users.
Addresses part of #77. Extracted from #67
=> Introduce `ObjectRef`

Ray.jl/src/object_store.jl, Ray.jl/src/runtime.jl, deps/wrapper.cc, deps/wrapper.h, src/wrappers/any.jl, test/put_get.jl, test/runtests.jl
Part of the work for #77. In order to specify object IDs contained within an object I needed to update our `put`/`get` wrapped functions. By updating these functions to pass in a `RayObject` these are more inline with the `ray::core::CoreWorker` interface and also allow me to specify the `nested_refs` argument for `RayObject`.
=> C++ wrapped `put`/`get` work with `RayObject`

Ray.jl/src/Ray.jl, Ray.jl/src/object_store.jl, Ray.jl/test/task.jl, deps/wrapper.cc, deps/wrapper.h, src/wrappers/any.jl, test/put_get.jl
This preserves the high-level behavior of `Ray.get` (blocks indefinitely until object is ready) while doing so in a way that does not hard lock the julia session.  Ultimately we'll also want to do something similar for `wait` (without actually trying to _fetch_ the results) but this is a fine stopgap for now.
---
- https://app.asana.com/0/0/1205391426815967
=> add timeout to `ray_jll.get` and make `Ray.get` short-poll every 100ms

Ray.jl/src/object_store.jl, Ray.jl/src/runtime.jl, Ray.jl/test/task.jl
=> Return `ObjectRef` from `submit_task`

LICENSE
The JLL has its own license but the main package does not.
=> Add a top-level license file

.github/workflows/ray_julia_jll_CI.yml
Matches what we already had for the Ray.jl build cache.
=> Include `ray_julia_jll` CI build cache name

test/object_store.jl, test/task.jl
Fixes #92. I temporarily set `ray_jll.get(oid, -1)` to validate these tests fail when C++ blocks.
=> Deterministic async `Ray.get` tests

ray_julia_jll/deps/wrapper.cc, ray_julia_jll/src/wrappers/any.jl, src/Ray.jl, src/object_ref.jl, src/object_store.jl, src/ray_serializer.jl, src/runtime.jl, src/serialize.jl, test/object_ref.jl, test/ray_serializer.jl, test/runtests.jl, test/runtime.jl, test/task.jl
Provides two main features:
- Support serializing `ObjectRef` via it's hex identifier
- Track `ObjectRef`s used within an `ObjectRef`
Fixes part of: https://github.com/beacon-biosignals/ray_core_worker_julia_jll.jl/issues/77
=> Support serializing `ObjectRef`

ray_julia_jll/deps/wrapper.cc, ray_julia_jll/test/function_descriptor.jl, ray_julia_jll/test/put_get.jl, ray_julia_jll/test/runtests.jl
This will provide support for `wait`/`isready`/`get` polling without data movement.
There's an additional output that I'm not capturing (whether something is local vs. in plasma store); I don't think that it's really necessary and we can always add a flag or another function to check for only local or only plasma later if need be.
=> wrap `CoreWorker::Contains`

ray_julia_jll/deps/wrapper.cc, ray_julia_jll/src/wrappers/any.jl, src/runtime.jl
Allows us to specify any inlined object references in the return.
=> Return a `RayObject` from `task_executor`

ray_julia_jll/deps/wrapper.cc, ray_julia_jll/src/wrappers/any.jl, src/object_ref.jl, test/task.jl
Was found to be useful in determining if an ObjectID has been registered with the core worker. If an `ObjectRef` does not have an owner then a `Ray.get` call will wait indefinitely. See https://github.com/beacon-biosignals/Ray.jl/issues/77#issuecomment-1712129853 for details.
=> Add `has_owner` accessor for `ObjectRef`

src/runtime.jl, test/ray_serializer.jl
The `GetObjectRefs` function requires that a `StdVector{ObjectID}` is passed in for the `inlined_ids` argument. If we update `serializer.object_ids` to return a `Set{ObjectID}` things break in an unexpected way as `StdVector(collect(Set{ObjectID}())) isa StdVector{Any}` where as `StdVector(collect(Set{ObjectIDAllocated}())) isa StdVector{ObjectID}`.
Here's an overview which may help those trying to understand what's going on:
```julia
julia> using ray_julia_jll: ObjectID, ObjectIDAllocated
julia> using CxxWrap.StdLib: StdVector
julia> StdVector(ObjectIDAllocated[])
0-element CxxWrap.StdLib.StdVectorAllocated{ObjectID}
julia> StdVector(ObjectID[])
0-element CxxWrap.StdLib.StdVectorAllocated{Any}
julia> StdVector{ObjectID}(ObjectIDAllocated[])
ERROR: MethodError: no method matching …
```
=> Ensure `inlined_ids` eltype of `StdVector` is correct

src/Ray.jl, src/ray_serializer.jl, test/ray_serializer.jl
While debugging a serialization issue with #77 it was noticed that `readheader` couldn't be called on a `RaySerializer`. This PR adds the `version` field so that this call succeeds.
Without this change a `deserialize(::RaySerializer)` call will fail. We haven't seen this issue before as we've only been using `RaySerializer` for serialization so far.
=> Support `readheader` with `RaySerializer`

src/runtime.jl
Allows us to merge https://github.com/beacon-biosignals/ray/pull/9 without breaking our Ray.jl CI.
=> Make `start_worker` positional argument optional

ray_julia_jll/Project.toml, ray_julia_jll/deps/wrapper.cc, ray_julia_jll/deps/wrapper.h, ray_julia_jll/src/wrappers/any.jl, ray_julia_jll/test/address.jl, ray_julia_jll/test/runtests.jl, src/runtime_env.jl
I had a couple notes on wrapping protobuf messages in Julia I wanted to add into our wrapper code and ended up implementing a wrapper for `google::protobuf::Message` which is the parent class of all of the `message X` protobuf code. Effectively this just makes it easier to wrap additional protobuf messages.
=> Wrap parent class for all protobuf messages

ray_julia_jll/deps/wrapper.cc, ray_julia_jll/src/wrappers/any.jl, ray_julia_jll/test/utils.jl, src/runtime.jl
- Wraps `JobID::FromInt` as `JobIDFromInt` instead of just `FromInt` to avoid future collisions (similar to what we did for `ObjectID`
- Implement `FromInt(::Type{JobID}, num::Integer)`
- Display `JobID` as a hexadecimal (via unsigned int)
- Use type assertion to ensure that `get_job_id` docstring is accurate
=> Tweaks to JobID

ray_julia_jll/deps/wrapper.cc, src/runtime.jl, src/runtime_env.jl, test/runtests.jl, test/runtime.jl, test/runtime_env.jl
Improves Julia driver support for Ray job submissions. Fixes this issue on the dashboard where a job submission and the driver are separate entries:
– https://github.com/beacon-biosignals/Ray.jl/pull/120#issuecomment-1724260426
=> Pass through metadata into JobConfig

.dockerignore, Dockerfile, ray_julia_jll/deps/build.jl
Creates an Ray.jl compatible alternative to the image `rayproject/ray:2.5.1-py310`. Additionally, this image features:
- Julia 1.9.3 pre-installed
- Ray.jl and ray_julia_jll.jl pre-installed based upon version in worktree
- Ray CLI from our https://github.com/beacon-biosignals/ray configurable via a build argument
- Docker caching for faster subsequent builds of ray_julia_jll and Ray CLI
There are additional tweaks that can be done here but the `Dockerfile` in its current form is functional and decently fast on subsequent builds. The image is currently x86_64 only at the moment as the `rayproject/ray` image requires the use of a separate tag for aarch64.
Uses the commit from https://github.com/beacon-biosignals/ray/pull/10. Ideally we'd merge that PR first and update the hardcoded …
=> Create Ray.jl `Dockerfile`

Dockerfile
While experimenting with our multi-node support with Ray.jl I noticed that the Docker image when deployed to K8s was performing precompilation even though we perform precompilation during the Docker image build.
From within the K8s head node I would see the following:
```sh
$ JULIA_DEBUG=loading julia -e 'using ray_julia_jll'
┌ Debug: Rejecting cache file /home/ray/.julia/compiled/v1.9/ray_julia_jll/u5r9n_66Sde.ji for ray_julia_jll [c348cde4-7f22-4730-83d8-6959fb7a17ba] since pkgimage can't be loaded on this target
└ @ Base loading.jl:2746
...
```
After a brief investigation I noticed that the `Sys.CPU_NAME` on my image build machine was `"znver3"` (AMD) while on my K8s head node it was `"cascadelake"` (Intel). The [official Julia binaries specify the CPU target …
=> Specify `JULIA_CPU_TARGET` for improved CPU compatibility

Project.toml, src/Ray.jl, src/exceptions.jl, src/object_store.jl, src/runtime.jl, test/exceptions.jl, test/runtests.jl, test/task.jl
Fixes: https://github.com/beacon-biosignals/Ray.jl/issues/135
Quick example:
```julia
julia> using Ray
julia> Ray.init()
julia> entrypoint = function (x)
function f(x)
if x > 3
throw(ErrorException("x > 3"))
else
Ray.get(Ray.submit_task(f, (x + 1,)))
end
end
return f(x)
end
#3 (generic function with 1 method)
julia> Ray.get(Ray.submit_task(entrypoint, (1,)))
ERROR: RayTaskException: Main.#3 (pid=11196, ip=192.168.224.76, task_id=c8ef45ccd0112571ffffffffffffffffffffffff01000000)
Stacktrace:
[1] _get(bytes::Vector{UInt8}, outer_obj_ref::ObjectRef)
@ Ray ~/.julia/dev/Ray/src/object_store.jl:59
[2] get(obj_ref::ObjectRef)
@ Ray ~/.julia/dev/Ray/src/object_store.jl:31
[3] top-level scope
@ REPL[4]:1
nested exception: RayTaskException: Serialization.__deserialized_types__.f (pid=11208, …
```
=> Improve display of task exceptions

.github/workflows/CI.yml, .github/workflows/ray_julia_jll_CI.yml, README.md, ray_julia_jll/Project.toml, ray_julia_jll/deps/Project.toml, ray_julia_jll/deps/build_jll.jl
Doing this avoids having Ray.jl users take on additional dependencies only needed for building the package from source. With this change we're also no longer using the pre-built binaries in CI. I think we should probably have tests for both building from source or from pre-built binaries but that should be a separate job/workflow. I'll do that as a follow up PR.
=> Use a separate project for `ray_julia_jll/deps`

.github/workflows/CI.yml, .github/workflows/ray_julia_jll_CI.yml
Uses a feature from this GitHub action to allow caching of Julia `.ji` files. Upstream issue: https://github.com/julia-actions/cache/issues/11
=> Use `cache-compiled` feature from `julia-actions/cache`

Dockerfile
Did a bunch of refactoring as part of this. The main change here was installing the Ray.jl package in `~/.julia/dev/Ray` to make it easier to access from other images. Additionally, this Dockerfile doesn't rely on using `JULIA_PROJECT` and instead adds Ray.jl to the default Julia environment.
=> Refactor `Dockerfile` to be useful as a base image for images

.github/workflows/CI.yml, Dockerfile, build/build_library.jl, build/ray_commit
In response to: https://github.com/beacon-biosignals/Ray.jl/pull/154#pullrequestreview-1649351425
By using a specific commit of `ray` in our `build_library.jl` script we can ensure that from source builds are full reproducible from any commit (from now on). We could just use the `WORKSPACE.bazel` to also do this but this allows us the flexibility to develop against a branch via `--no-checkout`
=> Use fixed version of ray-project

.gitignore, build/bind_artifacts.jl, build/build_tarballs.jl, build/common.jl, build/upload_tarballs.jl, docs/src/building-artifacts.md
In attempting to do our initial release I encountered a few issues with things being out of date.
As I worked through these issues I noticed that the artifacts we are uploading have very specific triplets. Normally, the triplets from BinaryBuilder are based upon `BinaryBuilder.supported_platforms()` which uses quite generic triplets and mainly focuses on OS and architecture. Having an overly specific triplet is an issue in that it can result in us generating more artifacts than we have to. I've reduced the triplet down to what should be the current minimum. Ideally, we wouldn't use the Julia version in our triplet but appears that our `WORKSPACE.bazel` setup is pulling in Julia specific headers which is resulting in shared libraries which are incompatible with other Julia version (I think …
=> Fixes to build scripts for initial release

.github/workflows/CI.yml, .github/workflows/Dockerfile.yml, .github/workflows/Documenter.yml, .github/workflows/FormatCheck.yml, .github/workflows/artifacts_CI.yml
Follow up to #170. As it turns out when a workflow is triggered via a tag the `path` filter is ignored: https://github.com/orgs/community/discussions/26273.
The official documentation for this isn't clear at all and really it seems to be documented via omission. The only documentation on this I found was:
> If you define both `branches`/`branches-ignore` and `paths`/`paths-ignore`, the workflow will only run when both filters are satisfied
– https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushbranchestagsbranches-ignoretags-ignore
=> Add CI comment about tags ignoring paths

docs/make.jl
The ["stable"](https://beacon-biosignals.github.io/Ray.jl/stable) documentation is still broken even after tagging `v0.0.1`. It looks like the culprit is the `versions` setting we had for [`deploydocs`](https://documenter.juliadocs.org/stable/lib/public/#Documenter.deploydocs). The default value for this function is `versions = ["stable" => "v^", "v#.#", "dev" => "dev"]`.
Unfortunately, the link will only be fixed when make a new tag.
=> Use default `versions` for `deploydocs`

.gitattributes
Makes the `WORKSPACE.bazel.tpl` classified as a Mustache file instead of a Smarty file in the GItHub language breakdown.
=> Classify WORKSPACE.bazel.tpl as Mustache

.github/workflows/CI.yml, .github/workflows/Dockerfile.yml, .github/workflows/artifacts_CI.yml
Using the newly announced M1 GHA runners: https://github.blog/2023-10-02-introducing-the-new-apple-silicon-powered-m1-macos-larger-runner-for-github-actions/. We should test against M1 in CI as it's one of the very limited platforms we support for Ray.jl and doing this should unlock the ability for automated artifact builds for making new releases.
I did some initial non-cache timings as part of another PR: https://github.com/beacon-biosignals/Ray.jl/pull/178#issuecomment-1743567864
=> Enable Apple silicon CI runners

src/ray_serializer.jl, test/ray_serializer.jl
This may help in debugging some of our sporadic task failures, where return objects do not deserialize correctly and which we suspect is due to un-handled metadata.
Eventually, in `deserialize_from_ray_object` we'll actually handle the known and relevant metadata cases, and this warning path will end up in a catchall `else` at the end.
=> log unhandled metadata

build/wrapper.cc, src/ray_julia_jll/common.jl, src/ray_julia_jll/expr.jl, test/ray_julia_jll/expr.jl, test/ray_julia_jll/runtests.jl
Split out from #184. Changes include:
- Be clearer in our `wrapper.cc` file where the enums come from (protobuf)
- Add `_enum_symbol_accessor_expr` function which generates `Symbol(::$Enum)` methods
- Make it easier to add all of the various helper enum methods
- Add tests for all of the `_enum_*` functions. This required introducing more `:block` expressions so that the expected expressions matched the generated ones.
=> Add support converting wrapper enums to `Symbol`

build/wrapper.cc, src/ray_julia_jll/common.jl
Split out from #184. This enum is needed to identify and handle errors from the raylet which are in the ray object. [Example of how these are used in Python](https://github.com/ray-project/ray/blob/a03efd9931128d387649dd48b0e4864b43d3bfb4/python/ray/_private/serialization.py#L289-L364).
Depends on #186.
=> Wrap `ErrorType` enum

build/wrapper.cc, src/ray_julia_jll/common.jl, src/ray_serializer.jl, test/ray_julia_jll/ray_object.jl, test/ray_julia_jll/runtests.jl, test/ray_serializer.jl
Split out from #184. Includes the following changes:
- Wraps `HasData` and `HasMetadata`
- Adds the function `get_data` and `get_metadata` as easy ways of fetching this data as `Vector{UInt8}`
- Support metadata in `serialize_to_ray_object`
- Throw an exception when encountering unhandled metadata. Avoids getting misleading error messages like in #143 but doesn't provide a nice user interface for what the metadata means.
The follow up to this PR will be parsing the metadata and either deserializing the data or returning an specific exception based upon the error type in the metadata (e.g. https://github.com/ray-project/ray/blob/a03efd9931128d387649dd48b0e4864b43d3bfb4/python/ray/_private/serialization.py#L263-L364)
=> Raise error when encountering unhandled metadata

Dockerfile
Refactoring this Dockerfile again to make it friendly for stacking Julia depots. Mainly this is useful for other Dockerfiles which want to copy out the Ray.jl installation for use in another image.
=> Use Julia depot stacking in our Dockerfile

src/Ray.jl, src/object_ref.jl, src/ray_julia_jll/common.jl, src/ray_julia_jll/ray_julia_jll.jl, src/ray_julia_jll/upstream_fixes.jl, test/object_ref.jl, test/object_store.jl, test/ray_julia_jll/address.jl, test/ray_julia_jll/runtests.jl, test/ray_julia_jll/upstream_fixes.jl, test/task.jl
While investigating #177 it was becoming evident that the flaw had something do with our worker addresses once again. As I so far have been unable to reproduce this problem locally I decided to look into audit our object reference ownership code to see if anything popped out. In doing so I recalled that in #140 we utilized JSON serialization for the owner address as we were having problems with CxxWrap `StdString` which would interpret the null-character as the end of the string instead of looking at the length of the string. The JSON approach doesn't actually fix anything except that it works around the issue. I decided to try to switch back to using `SerializeAsString` and apply our new CxxWrap knowledge to see if we could really fix the issue. In doing so I discovered that CxxWrap …
=> Improve robustness of `ObjectRef` ownership info serialization

src/object_ref.jl, src/ray_serializer.jl, test/object_ref.jl, test/object_store.jl, test/task.jl
Follow up to #203. Storing the owner address and the serialized object status in `ObjectRef` was rather strange as this information was only needed to finish the registration process after deserialization. This PR changes things to no longer be stored in `ObjectRef` but as part of the `RaySerializer` in a lookup table of object ref to ownership data.
Mainly this is just a refactoring of the existing code which should make it clearer that the extra `ObjectRef` fields are not needed all the time.
=> Store ownership info in `RaySerializer`

test/ray_julia_jll/buffer.jl
Closes: https://github.com/beacon-biosignals/Ray.jl/issues/55
=> Comment on use of `pointer_from_objref` in `LocalMemoryBuffer` tests

Project.toml, build/Project.toml, src/ray_serializer.jl
Uses the fix made in: https://github.com/JuliaInterop/CxxWrap.jl/pull/385
=> Use CxxWrap 0.14.2 for `StdVector` fix

test/runtime.jl, test/utils.jl
Use `process_eval` for all of our external Ray on Julia testing needs so that we get nicer reporting than this which was noticed on #214:
```
custom logs_dir: Error During Test at /Users/runner/work/Ray.jl/Ray.jl/test/runtime.jl:8
Got exception outside of a @test
failed process: Process(`/Users/runner/hostedtoolcache/julia/1.8.5/aarch64/bin/julia -Cnative -J/Users/runner/hostedtoolcache/julia/1.8.5/aarch64/lib/julia/sys.dylib --depwarn=yes --check-bounds=yes -g1 --code-coverage=user --color=yes --startup-file=no --project=/private/var/folders/ss/7dgwjb6s15n04v4v6nn0mxn00000gn/T/jl_OXOrae -e 'begin
#= /Users/runner/work/Ray.jl/Ray.jl/test/runtime.jl:12 =#
using Ray
#= /Users/runner/work/Ray.jl/Ray.jl/test/runtime.jl:13 =#
Ray.init(; logs_dir = …
```
=> Allow user capture of `stderr` in `process_eval`

build/wrapper.cc, build/wrapper.h, src/Ray.jl, src/constants.jl, src/function_manager.jl, src/runtime.jl, test/global_state_accessor.jl, test/runtests.jl, test/utils.jl
Break off of #202 
Closes #52 
- gcs address: `/tmp/ray/ray_current_cluster`
- node ip address: [const "127.0.0.1](https://github.com/ray-project/ray/blob/a03efd9931128d387649dd48b0e4864b43d3bfb4/python/ray/_private/services.py#L650-L658) (later it comes from its own file)
- raylet, store, port: GlobalStateAccessor
---
- https://app.asana.com/0/0/1205744051874128
- https://app.asana.com/0/0/1205770557599276
=> Parse ray runtime parameters from GlobalStateAccessor

build/wrapper.cc, build/wrapper.h, test/function_manager.jl, test/ray_julia_jll/gcs_client.jl
Follow up to #211 and fixes a long standing issue with locally testing with a persistent Ray head node between tests runs
=> GSC client refactor / Wrap `JuliaGcsClient::Del`

build/wrapper.cc, src/ray_julia_jll/common.jl, src/runtime.jl
Fixes #213 and may fix #143 
Given that we're still forbidding retries of application errors, I'm not quite sure how to test this.
=> pass `max_retries` during task submission

docs/make.jl, docs/src/getting-started.md, docs/src/installation.md, src/object_ref.jl
Improve the documentation in preparation for JuliaCon.
=> Fix pre-built installation instructions
